### PR TITLE
Filename plugin

### PR DESCRIPTION
**Pull request by r3ddr4gOn**
Hi, as discussed in the forums some time ago, I wrote a plugin which tags files by using the filename and want to share it. The plugin is disabled by default and only enabled, if the repository.ini contains the config parameters for it (commentary at the top of the source file). Please let me know if you think there is a better way to do this and i will try to change the code.

Best Regards
r3ddr4gOn

### CODE REVIEW

**Comment by StrumentiResistenti** [comment]
Hi r3ddr4gOn,

this is the configuration example you put in the source:

```
[filename]
filter=\.(DIRECTORSCUT|EXTENDED|UNCUT|1080p|720p|\d{4}|CUT|ENG|FR|DL|HD)
simple=DIRECTORSCUT,EXTENDED,UNCUT,1080p,720p,CUT,ENG,FR,DL,HD
machine=time:year:\d{4}
splitter=,
```

If I get it right, with the line "filter" you define a regexp which should match every possible tag encoded in the filename. This filter is iterated on the filename at line 172. Then you seem to apply simple tagging or machine tagging exclusively (line 186 excludes machine tagging if simple tagging is enabled). Is that right? And if so, why have you decided this way?

I would like to read more documentation and use cases, because I'm persuaded that a plugin that decodes tags from filenames could be really useful, but I'm not sure to fully undersand how you've developed yours.

**Comment by r3ddr4gOn** [comment]
I´m sorry I was a bit sloppy with my comments :)
I added another commit with more comments!

Yes you are right about the filter regexp. The first capturing group of the regexp is used for the possible tag names.

I wrote the exclusive tagging check just because I thought every tag-match should be only used once and I can´t really think of a machine-tag that uses the name of a simple tag as a value. But as there could be use-cases for this I removed the check. It´s not really problematic.

Currently I can´t think of another use case but there should be many possibilities with this design. But I really only developed the plugin for this use case and tried to keep it general.

**Comment by r3ddr4gOn** [comment]
Turns out there was another reason for the exclusive check. In the example, 1080p also matches the machine tag \d{4} which is obviously wrong. Therefore I added the ^ and $ to the machine-regex so it only matches the whole string.

Btw: if you want to have only one commit for this in the master branch I can squash all my commits into one. I don´t know how deep you dived into the git world yet so I thought I should mention it :).

**Comment by StrumentiResistenti** [comment]
I've merged your plugin. However I think that a more flexible one can be developed. By flexible I mean able to receive a set of rules formed by a pattern and a set of actions that use the matched tokens from the pattern to build an arbitrary number of tags, both simple and triple ones. I've started working on it and I plan to finish it in the next days. 

For now, thank you for your contribution. Is really appreciated. :)

**Pull request merged**
